{
 "title": "TDC Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Qtd. de Registros",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n count(*)\nFROM \"output-topic\"\nWHERE uf is not null",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n count(*)\\nFROM \\\"output-topic\\\"\\nWHERE uf is not null\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Valor medio vendas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n avg(\"value\" / 100) as valor_medio\nFROM \"output-topic\"\nWHERE uf is not null",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n avg(\\\"value\\\" / 100) as valor_medio\\nFROM \\\"output-topic\\\"\\nWHERE uf is not null\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Qtd. de registros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n TIME_FLOOR(__time, 'PT5M') AS t,\n COUNT(*) as qtd\nFROM \"output-topic\"\nWHERE uf is not null\nGROUP BY 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n TIME_FLOOR(__time, 'PT5M') AS t,\\n COUNT(*) as qtd\\nFROM \\\"output-topic\\\"\\nWHERE uf is not null\\nGROUP BY 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Valor total vendas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n TIME_FLOOR(__time, 'PT5M') AS t,\n sum(\"value\") / 10000 as total_vendas\nFROM \"output-topic\"\nWHERE uf is not null\nGROUP BY 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n TIME_FLOOR(__time, 'PT5M') AS t,\\n sum(\\\"value\\\") / 10000 as total_vendas\\nFROM \\\"output-topic\\\"\\nWHERE uf is not null\\nGROUP BY 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Qtd. de registros por Estado",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n\n uf,\n COUNT(*) as qtd\n\nFROM \"output-topic\"\nWHERE uf is not null\nGROUP BY 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n\\n uf,\\n COUNT(*) as qtd\\n\\nFROM \\\"output-topic\\\"\\nWHERE uf is not null\\nGROUP BY 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Total de vendas por bandeira",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n cardFlag,\n sum(\"value\" / 100) as total_vendas\nFROM \"output-topic\"\nWHERE uf is not null\nGROUP BY 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n cardFlag,\\n sum(\\\"value\\\" / 100) as total_vendas\\nFROM \\\"output-topic\\\"\\nWHERE uf is not null\\nGROUP BY 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}