apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
data:
  application.yml: |
    akhq:
      connections:
        strimzi-kafka:
          properties:
            bootstrap.servers: "kafka-cluster-kafka-bootstrap:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
      - name: akhq
        image: tchiotludo/akhq:0.25.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/application.yml
          subPath: application.yml
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"          
      volumes:
      - name: config-volume
        configMap:
          name: akhq-config
---
apiVersion: v1
kind: Service
metadata:
  name: akhq-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: akhq          